"""AUTOGENERATED FILE — DO NOT EDIT BY HAND."""

from typing import Protocol

import relationalai.semantics as rai

class Taxon(Protocol):
    id: rai.Relationship
    scientific_name: rai.Relationship
    canonical_name: rai.Relationship
    rank: rai.Relationship


class Observation(Protocol):
    id: rai.Relationship
    event_datetime: rai.Relationship
    day_of_year: rai.Relationship
    year: rai.Relationship
    basis_of_record: rai.Relationship
    country_code: rai.Relationship
    state_province: rai.Relationship
    latitude: rai.Relationship
    longitude: rai.Relationship
    h3_cell_6: rai.Relationship
    h3_cell_7: rai.Relationship
    h3_cell_8: rai.Relationship
    h3_cell_9: rai.Relationship
    h3_cell_10: rai.Relationship
    classification: rai.Relationship


class Plant(Protocol):
    id: rai.Relationship
    scientific_name: rai.Relationship
    reference: rai.Relationship


class Trait(Protocol):
    name: rai.Relationship
    value: rai.Relationship
