from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Sequence, Type

from kg.model.compiler.dsl import EntitySpec, _Field


@dataclass(frozen=True)
class GeneratedFile:
    path: str
    content: str


def _render_entity_protocol(spec: Type[EntitySpec]) -> str:
    entity = spec.__entity__
    fields: dict[str, _Field] = dict(spec.__fields__)

    # Always present
    lines: list[str] = [f"class {entity}(Protocol):"]
    lines.append("    id: rai.Relationship")

    for attr, field in fields.items():
        if field.kind == "key":
            continue
        # In this v0 generator, everything becomes a Relationship in typing.
        # (Even if it's a Property at runtime.) That's fine for autocomplete and
        # avoids over-specifying cardinality in typing.
        lines.append(f"    {attr}: rai.Relationship")

    if len(lines) == 2:
        lines.append("    pass")

    return "\n".join(lines)


def generate_protocol_module(*, specs: Sequence[Type[EntitySpec]]) -> str:
    """Generate Protocol classes for each EntitySpec.

    This is intentionally minimal: it generates entity Protocols only. Over time
    we can extend it to generate the ARQModel Protocol too.
    """

    body_parts: list[str] = []
    for spec in specs:
        body_parts.append(_render_entity_protocol(spec))

    body = "\n\n\n".join(body_parts).rstrip() + "\n"

    header = "\n".join(
        [
            "\"\"\"AUTOGENERATED FILE — DO NOT EDIT BY HAND.\"\"\"",
            "",
            "from typing import Protocol",
            "",
            "import relationalai.semantics as rai",
            "",
            "",
        ]
    )

    return header + body
